server:
  port: 8082

spring:
  application:
    name: notification
  datasource:
    url: jdbc:postgresql://localhost:5432/notification
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        diaflect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: false

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key